---
default_stages: ["commit"]
exclude: ^(.gitleaks\.toml|dist/.*\.js)$
repos:
  - repo: local
    hooks:
      - id: build
        name: Build
        entry: yarn run build
        language: system
        pass_filenames: false
        verbose: true
      - id: test
        name: Unit tests
        entry: yarn test
        language: system
        pass_filenames: false
        verbose: true
        stages: ["push"]
  # Security
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.3.0
    hooks:
      - id: detect-secrets
        stages: ["commit", "push"]
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.10.2
    hooks:
      - id: gitleaks
        stages: ["commit", "push"]
  - repo: https://github.com/fabasoad/pre-commit-snyk
    rev: v0.1.0
    hooks:
      - id: snyk-test
        stages: ["push"]
  # TypeScript
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.21.0
    hooks:
      - id: eslint
        args: ['--fix']
        files: \.[jt]sx?$
        types: [file]
        exclude: ^dist/.*\.js$
  # Markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.1
    hooks:
      - id: markdownlint
  # Yaml
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.27.1
    hooks:
      - id: yamllint
        args: ["-c", ".yamllint.yml"]
  # Other
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: check-json
      - id: detect-private-key
        stages: ["commit", "push"]
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: no-commit-to-branch
      - id: trailing-whitespace
ci:
  autofix_prs: false
  skip: [build, eslint, test]
