---
default_install_hook_types: ["pre-commit", "pre-push"]
default_stages: ["commit"]
exclude: ^(.gitleaks\.toml|dist/.*\.js)$
minimum_pre_commit_version: 2.18.0
repos:
  - repo: local
    hooks:
      - id: build
        name: Build
        entry: yarn run build
        language: system
        pass_filenames: false
        verbose: true
      - id: test
        name: Unit tests
        entry: yarn test
        language: system
        pass_filenames: false
        verbose: true
        stages: ["push"]
  # Security
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        stages: ["commit", "push"]
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.15.1
    hooks:
      - id: gitleaks
        stages: ["commit", "push"]
  - repo: https://github.com/fabasoad/pre-commit-snyk
    rev: v0.2.0
    hooks:
      - id: snyk-test
        stages: ["push"]
  # TypeScript
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.28.0
    hooks:
      - id: eslint
        args: ['--fix']
        files: \.[jt]sx?$
        types: [file]
        exclude: ^dist/.*\.js$
  # Markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.2
    hooks:
      - id: markdownlint
  # Yaml
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.28.0
    hooks:
      - id: yamllint
  # Other
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-json
      - id: detect-private-key
        stages: ["commit", "push"]
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: no-commit-to-branch
      - id: trailing-whitespace
ci:
  autofix_prs: true
  skip: [build, eslint, test]
