---
name: CI (latest)

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  unit_tests:
    name: Unit tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          ref: ${{ github.ref }}
      - uses: Adzz/jest_test_action@v1.0.0
        env:
          MICROSOFT_API_KEY: ${{ secrets.MICROSOFT_API_KEY }}
          MYMEMORY_API_KEY: ${{ secrets.MYMEMORY_API_KEY }}
          YANDEX_API_KEY: ${{ secrets.YANDEX_API_KEY }}
        with:
          package-manager: npm
          command: test
  functional_tests:
    name: Functional tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        source: ['Performance']    
      fail-fast: false
    steps:
      - uses: fabasoad/translation-action@${{ github.ref }}
        id: linguatools
        with:
          provider: linguatools
          lang: 'en-de'
          source: ${{ matrix.source }}
      - name: Validate Linguatools translation result
        run: |
          [[ "${{ steps.linguatools.outputs.text }}" == "Leistung" ]] || exit 1;
      - uses: fabasoad/translation-action@${{ github.ref }}
        id: microsoft
        with:
          provider: microsoft
          api_key: ${{ secrets.MICROSOFT_API_KEY }}
          lang: 'nl'
          source: ${{ matrix.source }}
      - name: Validate Microsoft translation result
        run: |
          [[ "${{ steps.microsoft.outputs.text }}" == "Prestaties" ]] || exit 1;
      - uses: fabasoad/translation-action@${{ github.ref }}
        id: mymemory_free
        with:
          provider: mymemory
          lang: 'en|pt'
          source: ${{ matrix.source }}
      - name: Validate MyMemory (Free) translation result
        run: |
          [[ "${{ steps.mymemory_free.outputs.text }}" == "Live performance" ]] || exit 1;
      - uses: fabasoad/translation-action@${{ github.ref }}
        id: mymemory_registered
        with:
          provider: mymemory
          api_key: ${{ secrets.MYMEMORY_API_KEY }}
          lang: 'en|it'
          source: ${{ matrix.source }}
      - name: Validate MyMemory (Registered) translation result
        run: |
          [[ "${{ steps.mymemory_registered.outputs.text }}" == "Svolgimento" ]] || exit 1;
      - uses: fabasoad/translation-action@${{ github.ref }}
        id: yandex
        with:
          provider: yandex
          api_key: ${{ secrets.YANDEX_API_KEY }}
          lang: 'en-tr'
          source: ${{ matrix.source }}
      - name: Validate Yandex translation result
        run: |
          [[ "${{ steps.yandex.outputs.text }}" == "Performans" ]] || exit 1;
