---
name: CI (latest)

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  unit_tests:
    name: Unit tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
        with:
          ref: ${{ github.ref }}
      - uses: Adzz/jest_test_action@v1.0.0
        env:
          MYMEMORY_API_KEY: ${{ secrets.MYMEMORY_API_KEY }}
          YANDEX_API_KEY: ${{ secrets.YANDEX_API_KEY }}
        with:
          package-manager: npm
          command: test
  functional_tests:
    name: Functional tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        source: ['Performance']    
      fail-fast: false
    steps:
      - uses: fabasoad/translation-action@v1.4.1
        id: linguatools
        with:
          provider: linguatools
          lang: 'en-de'
          source: ${{ matrix.source }}
      - name: Validate Linguatools translation result
        run: |
          echo "'${{ matrix.source }}' has been translated to '${{ steps.linguatools.outputs.text }}'"
          [[ "${{ steps.linguatools.outputs.text }}" == "Leistung" ]] || exit 1;
        shell: bash
      - uses: fabasoad/translation-action@v1.4.1
        id: mymemory_free
        with:
          provider: mymemory
          lang: 'en|pt'
          source: ${{ matrix.source }}
      - name: Validate MyMemory (Free) translation result
        run: |
          echo "'${{ matrix.source }}' has been translated to '${{ steps.mymemory_free.outputs.text }}'"
          [[ "${{ steps.mymemory_free.outputs.text }}" == "Live performance" ]] || exit 1;
        shell: bash
      - uses: fabasoad/translation-action@v1.4.1
        id: mymemory_registered
        with:
          provider: mymemory
          api_key: ${{ secrets.MYMEMORY_API_KEY }}
          lang: 'en|it'
          source: ${{ matrix.source }}
      - name: Validate MyMemory (Registered) translation result
        run: |
          echo "'${{ matrix.source }}' has been translated to '${{ steps.mymemory_registered.outputs.text }}'"
          [[ "${{ steps.mymemory_registered.outputs.text }}" == "Elevate" ]] || exit 1;
        shell: bash
      - uses: fabasoad/translation-action@v1.4.1
        id: funtranslations
        with:
          provider: funtranslations
          lang: 'klingon'
          source: ${{ matrix.source }}
      - name: Validate FunTranslations translation result
        run: |
          echo "'${{ matrix.source }}' has been translated to '${{ steps.funtranslations.outputs.text }}'"
          [[ "${{ steps.funtranslations.outputs.text }}" == "Performance" ]] || exit 1;
        shell: bash
