---
name: License

on: # yamllint disable-line rule:truthy
  schedule:
    # Every January 1st at 14:00 JST
    - cron: "0 5 1 1 *"

jobs:
  maintenance:
    name: Maintenance
    uses: fabasoad/reusable-workflows/.github/workflows/wf-update-license.yml@main
    permissions:
      contents: write
      pull-requests: write
